// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// TODO: use your own firebase_options.dart file, here I only left the interface itself, so you won't have to implement the interaction with it. 
/// Therefore, just replace this file and things will work
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError();
  }

  static FirebaseOptions get web {
    throw UnimplementedError();
  }
}
